### PR TITLE
feat: add circular overview + detail example

### PR DESCRIPTION
**Pull request by manzt**
Adds [Overview + Detail](https://gosling.js.org/?example=CIRCULAR_OVERVIEW_LINEAR_DETAIL) example. 

image

### CODE REVIEW

**Comment by manzt** [comment]
I'm having some issue with the linking here @sehilyi. I'm curious if this is something similar to the issue identified in #37...

**Comment by sehilyi** [comment]
This looks indeed an issue with `overlay` in Gosling. Similar to #37, when I move `data` to the parent, brushes are properly shown. Let me closer look at Gosling.

**Comment by manzt** [comment]
Up to you whether or not we can/should merge. It seems like something we should resolve outside of this PR, since it will be in gosling.js.

**Review by sehilyi — APPROVED** [review]
Yes, we should merge. The issues turn out to be only gosling.js' issues and the PR looks great. I will merge the two PRs.

**Pull request merged**
